# Generated by Django 3.2.5 on 2021-09-08 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='カテゴリ')),
                ('summary', models.TextField(verbose_name='概要')),
                ('relation', models.ManyToManyField(blank=True, null=True, related_name='_edu_category_relation_+', to='edu.Category', verbose_name='関連')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='分野')),
                ('summary', models.TextField(verbose_name='概要')),
                ('relation', models.ManyToManyField(blank=True, null=True, related_name='_edu_line_relation_+', to='edu.Line', verbose_name='関連')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('summary', models.TextField(verbose_name='概要')),
                ('description', models.TextField(verbose_name='詳細')),
                ('thumbnail', models.ImageField(upload_to='jobimages', verbose_name='サムネイル')),
                ('image1', models.ImageField(upload_to='jobimages', verbose_name='学習ロードマップ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='リンク先URL')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu.line', verbose_name='分野')),
                ('relation', models.ManyToManyField(blank=True, null=True, to='edu.Category', verbose_name='関連学習カテゴリ')),
                ('relationjob', models.ManyToManyField(blank=True, null=True, related_name='_edu_jobpost_relationjob_+', to='edu.JobPost', verbose_name='キャリアプラン')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='EduPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='講義名')),
                ('organizer', models.CharField(max_length=200, verbose_name='主催団体')),
                ('summary', models.TextField(verbose_name='概要')),
                ('description', models.TextField(verbose_name='詳細')),
                ('thumbnail', models.ImageField(upload_to='eduimages', verbose_name='サムネイル')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='eduimages', verbose_name='イメージ1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='eduimages', verbose_name='イメージ2')),
                ('link', models.URLField(blank=True, null=True, verbose_name='申込み先URL')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edu.category', verbose_name='カテゴリ')),
                ('jobinfo', models.ManyToManyField(blank=True, null=True, to='edu.JobPost', verbose_name='受講推奨職種')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
    ]
